sudo: false

os:
  - linux
  - osx

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.9
    - g++-4.9
    - uuid-dev

language: node_js
node_js:
  - "7"
  - "6"

env:
  global:
  - CXX=g++-4.9
  - CC=gcc-4.9
  matrix:
  - ZMQ="4.1.6" ZMQ_REPO="zeromq4-1"

before_install:
 - mkdir ldlocal
 - export LDHACK=`pwd`/ldlocal
 - export LD_RUN_PATH=$LDHACK/lib
 - export LD_LIBRARY_PATH=$LDHACK/lib
 - export PKG_CONFIG_PATH=$LDHACK/lib/pkgconfig
 - wget https://github.com/zeromq/$ZMQ_REPO/releases/download/v$ZMQ/zeromq-$ZMQ.tar.gz
 - tar xzvf zeromq-$ZMQ.tar.gz
 - cd zeromq-$ZMQ
 - ./autogen.sh
 - ./configure --prefix=$LDHACK --without-libsodium
 - make -j
 - make install
 - cd ..

before_script:
  - npm install -g gulp
script: gulp
